main/views.py
import os

from flask import Blueprint, render_template, request, g, send_from_directory
from flask import current_app

from main import db
from .utils import get_class_by_tablename, get_pdf_report, paginate

main = Blueprint('main', __name__)


@main.route('/report/<path:filename>', methods=['GET', 'POST'])
def download(filename):
    filename = get_pdf_report()
    path_to_file = os.path.join(current_app.template_folder, 'report')
    return send_from_directory(directory=path_to_file, filename=filename)


@main.route('/', methods=['GET', 'POST'])
@main.route('/<brand>', methods=['POST', 'GET'])
def home(brand='samsung'):
    brand = get_class_by_tablename(brand)
    if g.user and request.method == 'POST':
        model_id_to_del = request.form['model-id-delete']
        obj_to_del = brand.query.get(model_id_to_del)
        if obj_to_del:
            db.session.delete(obj_to_del)
            db.session.commit()

    page = request.args.get('page', 1, type=int)
    search_query = request.args.get('search')
    models = paginate(brand.query, page)
    if search_query:
        # TODO remove pagination logical from brand.search
        models, total = brand.search(search_query, page, 3)
        models = paginate(models, page)
    return render_template('home/home.html', models=models, brand=brand)


@main.before_app_first_request
def setup_application():
    db.create_all()

templates/home/home.html
{% extends 'base.html' %}
{% block title %}Платы для телевизора {{ brand.__tablename__ }}{% endblock %}
{% block home %}
    {% include 'header.html' %}
    <div class="main">
        <div class="row">
            <div class="col-md-12">
                <div class="search-form">
                    <form method="GET">
                        <input type="search" name="search"
                               placeholder="искать в: {{ brand.__tablename__ }}">
                        <input class="button" type="submit" value="Искать">
                    </form>
                </div>
            </div>
        </div>
        <div class="brands">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <ul>
                        <li><a href="{{ url_for('main.home',
                                brand='samsung') }}">Samsung</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='lg') }}">Lg</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='horizont') }}">Горизонт</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='vityaz') }}">Витязь</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='philips') }}">Philips</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <ul>
                        <li><a href="{{ url_for('main.home',
                                brand='toshiba') }}">Toshiba</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='tomson') }}">Tomson</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='sharp') }}">Sharp</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='sony') }}">Sony</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='panasonic') }}">Panasonic</a></li>

                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <ul>
                        <li><a href="{{ url_for('main.home',
                                brand='bbk') }}">Bbk</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='shinco') }}">Shinco</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='dynex') }}">Dynex</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='manta') }}">Manta</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='dell') }}">Dell</a></li>

                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <ul>
                        <li><a href="{{ url_for('main.home',
                                brand='daevoo') }}">Daevoo</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='shivaki') }}">Shivaki</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='supra') }}">Supra</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='grundic') }}">Grundic</a></li>
                        <li><a href="{{ url_for('main.home',
                                brand='telefunken') }}">Telefunken</a></li>
                    </ul>
                </div>
            </div>
        </div>
        {% if models.items %}
            <div class="model-list">
                {% for model in models.items %}
                    <div class="model">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <ul data-id="{{ model.id }}"
                                    class="model-title model-title-{{ model.id }}">
                                    <li>
                                        <a class="model-title-link" href="#">{{ model.model }}
                                        </a>
                                    </li>
                                </ul>
                                <ul data-id="{{ model.id }}"
                                    class="model-detail model-detail-{{ model.id }}">
                                    <li>
                                        Power:<span>{{ model.power }}</span>
                                    </li>
                                    <li>
                                        T-con:<span>{{ model.t_con }}</span>
                                    </li>
                                    <li>
                                        Main:<span>{{ model.main }}</span>
                                    </li>
                                    <li>
                                        X-main<span>{{ model.x_main }}</span>
                                    </li>
                                    <li>Y-main:
                                        <span>{{ model.y_main }}</span>
                                    </li>
                                    <li>Logic:<span>{{ model.logic }}</span></li>
                                    <li>Inverter:<span>{{ model.invertor }}</span>
                                    </li>
                                    <li>Led-driver:<span>{{ model.led_driver }}</span></li>
                                    <li>Y-scan:<span>{{ model.y_scan }}</span>
                                    <li>Y-sus:<span>{{ model.y_sus }}</span>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination">
                {% if models.pages > 1 %}
                    <ul>
                        {% if models.has_prev %}
                            <li><a href="?page={{ models.prev_num }}">Prev</a>
                            </li>
                        {% else %}
                            <li><a href="#">Prev</a></li>
                        {% endif %}
                        {% for page in models.iter_pages() %}
                            {% if page != models.page %}
                                <li><a href="?page={{ page }}">{{ page }}</a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="?page={{ page }}"
                                       class="active">{{ page }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if models.has_next %}
                            <li><a href="?page={{ models.next_num }}">Next</a>
                            </li>
                        {% else %}
                            <li><a href="#">Next</a></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        {% else %}
            <div class="nothing-to-show">
                <h1>Упс, похоже нет плат для данного бренда</h1>
                <h2>Убедитесь в том, что запрос введен верно</h2>
            </div>
        {% endif %}
        <div class="report">
            <div class="row">
                <a href="{{ url_for('main.download', filename='report.pdf') }}" class="button download" download>Скачать
                    каталог</a>
            </div>
        </div>
    </div>
    {% include 'footer.html' %}

{% endblock %}

templates/home/login.html
{% extends 'base.html' %}
{% block login %}
    <div class="login">
        <form method="POST" name="login">
            <label for="username">Имя:</label>
            <input type="text" name="username" id="username" required>

            <label for="password">Пароль:</label>
            <input type="password" name="password" id="password" required>
            <div class="errors">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        <ul class=flashes>
                            {% for category, message in messages %}
                                <li class="{{ category }}">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endwith %}
            </div>
            <input type="submit" value="Отправить" class="button">
        </form>
    </div>
{% endblock %}